services:

  storage_mongo:
    image: mongo 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: advertisement
    volumes:
      - ./data/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 

  advertisement:
    image: demon62/kr1:advertisement-v1.0.0
    ports: 
      - 80:${PORT}
    environment: 
      - MONGO_URL=mongodb://storage_mongo:27017/advertisement
    env_file:
      - .env
    depends_on: 
      - storage_mongo 